apiVersion: v1                #Service resource is under the scope of v1
kind: Service                 #one type of networking resource that can be deployed in k8s nodes. 
metadata:
  name: frontend-service      #name of the service.
spec:
  selector:                   #targets all resources whose labels match key-value pair. limited to exact match.
    component: frontend    
  type: NodePort              #UNSAFE for production
  ports:
  - port: 3001                #listening port of this service. Other k8s resources can connect to this service on this port.
    targetPort: 3000          #destination port. this port on target pod/resource will be served by this service. target pod must have a container that is listening on the same portnumber.
    nodePort: 30002           #listening port of the node where service is deployed. Accessing the hostname/IP/DNS of the node on this port will expose this service. Range=30000-32767. UNSECURE