services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./:/opt/react_project
      - node_modules:/opt/react_project/node_modules
volumes:
  node_modules:
    external: true